### ISSUE TITLE
Unable to deploy limit monitor solution   - Lambda function logs shows  - INFO [ERROR]ParameterNotFound: null

### ISSUE THREAD

**Issue by puramashok2013** [awslabs/aws-limit-monitor#34]
I gave below parameters while creating stack 
SlackChannel : slacknotifier 
SlackHookURL :https://hooks.slack.com/services/xxxxxx/xxx/xxxx

CF created only one parameter in parameter store as - slacknotifier and value as slack_dummy.

**Result** : Lambda function logs shows  - INFO [ERROR]ParameterNotFound: null

Let me know what we need to do to solve this issue ?
**Let me know key, value pairs to be created in parameter store.**

**Comment by kenmick** [comment]
@puramashok2013 
Actually the value of these two parameters should be SSM keys instead of their values. You need to set their values in AWS System Manager - Parameter Store. 
For instance
```
Parameters for creating stack
SlackChannel: SLACK_CHANNEL
SlackHookURL: SLACK_HOOK_URL

Parameters in AWS System Manager - Parameter Store
SLACK_CHANNEL: slacknotifier
SLACK_HOOK_URL: https://hooks.slack.com/services/xxxxxx/xxx/xxxx
```

Besides, don't forget to check the Environment Variables of the SlackNotifier Lambda. They should be incorrect according to your current configuration.

**Comment by gsingh04** [comment]
@puramashok2013 please follow steps mentioned by @kenmick 
you may also check our troubleshooting section [here](https://docs.aws.amazon.com/solutions/latest/limit-monitor/appendix-a.html)

**Comment by georgebearden** [comment]
Please let us know if you need additional assistance with this.
