### ISSUE TITLE
Cannot find module 'uuid/v4'

### ISSUE THREAD

**Issue by SpyderDave** [awslabs/aws-limit-monitor#49]
Got this error:
 Cannot find module 'uuid/v4' when invoking the helper function.

Easy fix. 
const uuidv4 = require('uuid').v4;

**Comment by gsingh04** [comment]
Hello,

Thanks for your feedback. 

I believe the reason is mentioned [here](https://github.com/uuidjs/uuid#deep-requires-no-longer-supported).

Our deployment package is based of previous uuid version, hence if you use our existing solution it will not report the issue. But if you try to make custom install and make the deployment package again `npm install` would install the new version and break the implementation.

We will fix this in our next release.

Please continue to monitor the repo for updates.

**Comment by solsglasses** [comment]
I created a PR to fix this, before seeing this issue was created

https://github.com/awslabs/aws-limit-monitor/pull/55
